---
abstract: 'Command line utilities to use with SAPO Broker'
author:
  - 'Pedro Melo, C<< <melo at cpan.org> >>'
distribution_type: module
generated_by: 'Module::Install version 0.760'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-SAPO-Broker
no_index:
  directory:
    - inc
    - t
requires:
  Benchmark: 0
  Class::Accessor::Fast: 0
  Getopt::Long: 0
  IO::String: 0
  LWP::UserAgent: 0
  Net::SAPO::Broker: 0.01
  Time::HiRes: 0
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/melo/perl-sapo-broker
version: 0.01
