---
abstract: 'Command line utilities to use with SAPO Broker'
author:
  - 'Pedro Melo <melo@simplicidade.org>'
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-SAPO-Broker-Utils
no_index:
  directory:
    - inc
    - t
requires:
  Getopt::Long: 0
  Net::SAPO::Broker: 0.01
  Time::HiRes: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/melo/perl-sapo-broker
version: 0.01
