---
abstract: 'The great new Protocol::SAPO::Broker!'
author:
  - 'Pedro Melo, C<< <melo at cpan.org> >>'
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Protocol-SAPO-Broker
no_index:
  directory:
    - inc
    - t
requires:
  Carp::Clan: 0
  Class::Accessor::Fast: 0
  Errno: 0
  Test::Most: 0
  XML::LibXML: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/melo/perl-sapo-broker
version: 0.01
