---
abstract: 'The great new Net::SAPO::Broker!'
author:
  - 'Pedro Melo, C<< <melo at cpan.org> >>'
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SAPO-Broker
no_index:
  directory:
    - inc
    - t
requires:
  Carp::Clan: 0
  Errno: 0
  Protocol::SAPO::Broker: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
